### ISSUE TITLE
silence db is abount -51db

### ISSUE THREAD

**Issue by deyituo** [aask1357/hilcodec#1]
I find the decoded wav's silence offset to about -51db, do you have any idea about it ?

![image](https://github.com/aask1357/hilcodec/assets/19730584/4dbb539e-ccda-4040-81b5-22e299e5a674)

**Comment by aask1357** [comment]
Can you provide the input audio file? I will check.
I guess you used a `test_onnx.py` script with `hilcodec_speech` checkpoint, right?

**Comment by deyituo** [comment]
You can get the wav I tested here:

https://drive.google.com/drive/folders/1rxjl792RwaEVMv3igB2Wztcy-924gx2-?usp=sharing

**Comment by aask1357** [comment]
Thank you for sharing your observation!
After hearing, we suspect that -50dB offset is inaudible in normal cases.
However, there may be some situations where silence should have 0 offset.
Here are some solutions I suggest:
1. Add time-domain loss term. Currently, we only use spectrogram losses and GAN losses. If we add a time-domain loss term as in the EnCodec, the silence offset may be lower.
2. Remove the bias parameter in the final convolution layer of the decoder and then train. Currently, the value of the bias of the final convolution is "0.0034", which can be the cause of the non-zero silence offset.
![waveform](https://github.com/aask1357/hilcodec/assets/13253928/7e3eed99-c169-4a1e-963e-7feaaff64cc0)
